.\"
.\" permasign.1
.\" Copyright (c) 2022 TheRealKeto
.\"
.\" SPDX-License-Identifier: BSD-3-Clause
.\" Created by TheRealKeto on 9/2/2022.
.\"
.Dd October 24, 2022
.Dt PERMASIGN 1
.Os
.Sh NAME
.Nm permasign
.Nd Permanently sign any iOS app
.Sh SYNOPSIS
.Nm permasign
.Fl i , -ipa Ar FILE
.Fl e , -entitlements Ar ENTS
.Fl k , -certificate Ar CERT
.Op Fl z , -zip
.Sh DESCRIPTION
.Nm permasign
is a command-line interface, that also functions as a library,
which utilizes
.Xr ldid 1
in order to permanently sign any iOS app.
.Pp
Due to a bug within CoreTrust found by
.An Linus Henze
& exploited by
.An zhowei ,
it's possible to permanently sign any iOS (as well as macOS)
app, bypassing the common 7-day period assigned to any
application when sideloading it with a non-developer Apple
account.
.Pp
Sadly, only several individuals are capable of taking advantage
of this command-line interface, as the target device (the device
where you want to install any permanently signed iOS app) must
be jailbroken.
This is due to the fact that, after using
.Nm permasign ,
you're still required to put the signed app bundle within the
Applications folder in the root of the device's filesystem, which
non-jailbroken iOS does not provide access to.
.Pp
The following options are supported by
.Nm permasign :
.Bl -tag -width -indent
.It Fl h , -help
Print a synopsis and all available commands.
.It Fl V , -version
Print the current version of
.Nm permasign .
.It Fl i , -ipa Ar FILE
Specify the path of the iOS app you want to sign.
.Pp
.Ar FILE
refers to the iOS app you want to sign, which can be a direct
path to any iOS app (.ipa) within your system.
This option is required.
.Pp
Once the given
.Ar FILE
is signed with
.Xr ldid 1 ,
.Nm permasign
will optionally bundle it in a ZIP archive.
The created archive contains the signed app bundle, which can
be moved to the Applications folder (/Applications) in order
for it to be shown on your homescreen.
.It Fl e , -entitlements Ar ENTS
Specify entitlements that
.Xr ldid 1
should apply when signing.
.Pp
.Ar ENTS
refers to any file in XML format (.xml, .plist) that contains
any entitlements that
.Xr ldid 1
will apply after the app bundle is extracted from the given
iOS app.
This option is required.
.It Fl k , -certificate Ar CERT
Local certificate that permanently signs the given iOS app.
.Pp
.Ar CERT
refers to the certificate that
.Xr ldid 1
will use when signing the app bundle of the given iOS app.
This option is required.
.It Fl z , -zip
Create an archive of the signed iOS app bundle.
.Pp
When used,
.Nm permasign
will create a ZIP archive of the extracted app bundle after
it has been signed by
.Xr ldid 1 .
This behavior is optional.
.El
.Sh SEE ALSO
.Xr ldid 1 ,
.Xr uicache 1
.Sh HISTORY
.Nm permasign
is an alternative project that somewhat rivals
.Nm permasigner ,
which was written by
.An nebula (itsnebulalol) .
.Pp
.Nm permasign
is a side project meant to have a much cleaner codebase than
.Nm permasigner ,
and while it's not as extensive as its alternatives, it attempts
to provide a product without many dependencies while also being
entirely multi-platform.
.Nm permasign
only depends on
.Xr ldid 1 ,
specifically distributed by the
.An Procursus Team Aq Mt support@procurs.us .
.Sh AUTHORS
.Nm permasign
was written with the Python Programming Language by
.An TheRealKeto Aq Mt therealketo@gmail.com .
.Sh BUGS
With the
.Fl k , -certificate
flag, certificates whose passphrase is anything other than
"password" will not be accepted.
