[tool.poetry]
name = "permasign"
version = "1.0.0"
description = "Permanently sign any IPA on jailbroken devices"
authors = ["TheRealKeto <therealketo@gmail.com>"]
license = "BSD-3-Clause"
repository = "https://github.com/TheRealKeto/Permasign"

[tool.poetry.scripts]
permasign = "permasign.cli:cli"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
pyright = "^1.1.268"

[tool.pyright]
ignore = [
	"dist",
	"env",
	"**/__pycache__",
	"permasign/cli.py"
]
pythonVersion = "3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
